In [1]:
import pandas as pd


df = pd.read_csv('인천광역시.csv' , encoding = 'cp949')
df_2 = pd.read_csv('../../../../데이터센터정리.csv' , encoding = 'cp949')

df = df.astype({'시군구법정동번지코드' : 'str',
                '시군구법정동번코드' : 'str'})
df.head()

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,본번,부번,사용량_KWH,시도명,시군구명,법정동명,새주소대로로코드,새주소대로로명,새주소본번,새주소부번
0,283956,282001010012773,28200101001277,2820010100,1277,3,569,인천광역시,남동구,구월동,282004259750.0,호구포로764번길,9.0,1.0
1,317751,287203802131,28720380213,2872038021,3,1,513,인천광역시,옹진군,연평면 연평리,287203158026.0,연평로,314.0,7.0
2,284782,28200102005802,2820010200580,2820010200,580,2,2941,인천광역시,남동구,간석동,282003151030.0,석정로,576.0,0.0
3,284781,28200102005800,2820010200580,2820010200,580,0,5390,인천광역시,남동구,간석동,282003151030.0,석정로,580.0,0.0
4,284780,28200102005756,2820010200575,2820010200,575,6,6,인천광역시,남동구,간석동,282004259465.0,석정로580번길,28.0,0.0

In [2]:
df_2.head()

,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,421301170018946,42130117001894,4213011700,1894,6,강원 원주시 건강로 32(반곡동 1894-6),공공,국민건강보험공단,국민건강보험공단 데이터센터,O 자체 데이터센터,-,NaN
1,4213011700204710,42130117002047,4213011700,2047,14,강원 원주시 입춘로 130(반곡동 2047-14),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (2사옥),-,-,NaN
2,4213011700204710,42130117002047,4213011700,2047,10,강원 원주시 혁신로 60(반곡동 2047-10),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (1사옥),-,-,NaN
3,421103102210000,42110310221000,4211031022,1000,0,강원 춘천시 동면 순환대로 1231,민간,NAVER,네이버 데이터센터 각,수력 발전소 통해 전체 전력량 70% 수급,-,NaN
4,42110126006500,4211012600650,4211012600,650,0,강원도 춘천시 옛경춘로 409-14,민간,오라클 춘천,오라클 춘천,-,-,NaN

In [3]:
df_3 = pd.merge(df, df_2, how='inner' , on='시군구법정동번지코드')

df_3

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드_x,시군구법정동코드_x,본번,부번,사용량_KWH,시도명,시군구명,법정동명,...,시군구법정동코드_y,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,271043,281101470028500,28110147002850,2811014700,2850,0,36863185,인천광역시,중구,운서동,...,2811014700,2850,0,인천 중구 공항로 272 인천국제공항여객터미널,공공,인천공항출입국·외국인청,T1 전산실,-,-,NaN
1,271043,281101470028500,28110147002850,2811014700,2850,0,36863185,인천광역시,중구,운서동,...,2811014700,2850,0,인천 중구 공항로 272 인천국제공항여객터미널,공공,인천공항출입국·외국인청,T2 전산실,-,-,NaN
2,271043,281101470028500,28110147002850,2811014700,2850,0,36863185,인천광역시,중구,운서동,...,2811014700,2850,0,인천 중구 공항로424번길 47,공공,인천국제공항공사,서버실-1,-,-,NaN
3,305135,282601220075,28260122007,2826012200,7,5,3273408,인천광역시,서구,청라동,...,2826012200,7,5,인천광역시 서구 에코로 181,금융,하나금융,하나금융그룹 통합데이터센터,-,-,NaN
4,295331,28245101002361,2824510100236,2824510100,236,1,1858752,인천광역시,계양구,효성동,...,2824510100,236,1,"인천 계양구 아나지로213번길 23, 인천광역시 계양구 효성동 236-1",민간,LG CNS,인천센터,-,-,NaN

In [4]:
df_3.to_csv("인천광역시_전력사용량.csv" , mode = 'w' , encoding= 'cp949')