In [1]:
import pandas as pd


df = pd.read_csv('대구광역시.csv' , encoding = 'cp949')
df_2 = pd.read_csv('../../../../데이터센터정리.csv' , encoding = 'cp949')

df = df.astype({'시군구법정동번지코드' : 'str',
                '시군구법정동번코드' : 'str'})
df.head()

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,본번,부번,사용량_KWH,시도명,시군구명,법정동명,새주소대로로코드,새주소대로로명,새주소본번,새주소부번
0,233788,2717010900143410,27170109001434,2717010900,1434,10,6835,대구광역시,서구,원대동3가,271704229107.0,달서로54길,11.0,0.0
1,233781,271701090013233,27170109001323,2717010900,1323,3,717,대구광역시,서구,원대동3가,271703143002.0,달서로,286.0,0.0
2,233782,271701090013275,27170109001327,2717010900,1327,5,7,대구광역시,서구,원대동3가,271703007024.0,팔달로,232.0,0.0
3,233783,2717010900135924,27170109001359,2717010900,1359,24,7,대구광역시,서구,원대동3가,271703007024.0,팔달로,210.0,0.0
4,233784,271701090013673,27170109001367,2717010900,1367,3,24106,대구광역시,서구,원대동3가,271703007024.0,팔달로,176.0,0.0

In [2]:
df_2.head()

,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,421301170018946,42130117001894,4213011700,1894,6,강원 원주시 건강로 32(반곡동 1894-6),공공,국민건강보험공단,국민건강보험공단 데이터센터,O 자체 데이터센터,-,NaN
1,4213011700204710,42130117002047,4213011700,2047,14,강원 원주시 입춘로 130(반곡동 2047-14),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (2사옥),-,-,NaN
2,4213011700204710,42130117002047,4213011700,2047,10,강원 원주시 혁신로 60(반곡동 2047-10),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (1사옥),-,-,NaN
3,421103102210000,42110310221000,4211031022,1000,0,강원 춘천시 동면 순환대로 1231,민간,NAVER,네이버 데이터센터 각,수력 발전소 통해 전체 전력량 70% 수급,-,NaN
4,42110126006500,4211012600650,4211012600,650,0,강원도 춘천시 옛경춘로 409-14,민간,오라클 춘천,오라클 춘천,-,-,NaN

In [3]:
df_3 = pd.merge(df, df_2, how='inner' , on='시군구법정동번지코드')

df_3

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드_x,시군구법정동코드_x,본번,부번,사용량_KWH,시도명,시군구명,법정동명,...,시군구법정동코드_y,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,238907,272001020062715,2720010200627,2720010200,627,15,433675,대구광역시,남구,봉덕동,...,2720010200,627,15,대구시 남구 봉덕로 61 (봉덕동 627-15) KT봉덕지사 2층,통신,"KT,대구달성군시설관리공단",KT 대구 IDC,-,-,NaN
1,218780,27110101002951,2711010100295,2711010100,295,1,297792,대구광역시,중구,동인동1가,...,2711010100,295,1,대구광역시 중구 동덕로 186,통신,LG U+,LG U+대구 센터,기타분류,-,NaN

In [4]:
df_3.to_csv("대구광역시_전력사용량.csv" , mode = 'w' , encoding= 'cp949')