In [1]:
import pandas as pd


df = pd.read_csv('강원도.csv' , encoding = 'cp949')
df_2 = pd.read_csv('../../../../데이터센터정리.csv' , encoding = 'cp949')

df = df.astype({'시군구법정동번지코드' : 'str',
                 '시군구법정동번코드' : 'str'})
df.head()

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,본번,부번,사용량_KWH,시도명,시군구명,법정동명,새주소대로로코드,새주소대로로명,새주소본번,새주소부번
0,681461,42110310222801,4211031022280,4211031022,280,1,10167,강원도,춘천시,동면 만천리,421103218054.0,한솔만천로,15.0,3.0
1,729740,42720370238114,4272037023811,4272037023,811,4,646,강원도,홍천군,서면 팔봉리,427204475481.0,오도치길,6.0,0.0
2,729739,42720370238113,4272037023811,4272037023,811,3,1007,강원도,홍천군,서면 팔봉리,427204475627.0,한치골길,820.0,0.0
3,729738,42720370237506,4272037023750,4272037023,750,6,4225,강원도,홍천군,서면 팔봉리,427204475627.0,한치골길,702.0,0.0
4,729737,42720370237290,4272037023729,4272037023,729,0,1369,강원도,홍천군,서면 팔봉리,427204475627.0,한치골길,652.0,27.0

In [2]:
print(df.dtypes)

Unnamed: 0     int64
시군구법정동번지코드    object
시군구법정동번코드     object
시군구법정동코드       int64
본번             int64
부번             int64
사용량_KWH        int64
시도명           object
시군구명          object
법정동명          object
새주소대로로코드      object
새주소대로로명       object
새주소본번         object
새주소부번         object
dtype: object

In [3]:
#df_2 = df_2.astype({'시군구법정동번지코드' : 'float'})

In [4]:
print(df_2.dtypes)

시군구법정동번지코드     object
시군구법정동번코드      object
시군구법정동코드        int64
번              object
지              object
주소             object
분류             object
기업             object
이름             object
비고             object
임차여부           object
전력사용량         float64
dtype: object

In [5]:
df_2.head()

,시군구법정동번지코드,시군구법정동번코드,시군구법정동코드,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,421301170018946,42130117001894,4213011700,1894,6,강원 원주시 건강로 32(반곡동 1894-6),공공,국민건강보험공단,국민건강보험공단 데이터센터,O 자체 데이터센터,-,NaN
1,4213011700204710,42130117002047,4213011700,2047,14,강원 원주시 입춘로 130(반곡동 2047-14),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (2사옥),-,-,NaN
2,4213011700204710,42130117002047,4213011700,2047,10,강원 원주시 혁신로 60(반곡동 2047-10),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (1사옥),-,-,NaN
3,421103102210000,42110310221000,4211031022,1000,0,강원 춘천시 동면 순환대로 1231,민간,NAVER,네이버 데이터센터 각,수력 발전소 통해 전체 전력량 70% 수급,-,NaN
4,42110126006500,4211012600650,4211012600,650,0,강원도 춘천시 옛경춘로 409-14,민간,오라클 춘천,오라클 춘천,-,-,NaN

In [6]:
df_3 = pd.merge(df, df_2, how='inner' , on='시군구법정동번지코드')

df_3

,Unnamed: 0,시군구법정동번지코드,시군구법정동번코드_x,시군구법정동코드_x,본번,부번,사용량_KWH,시도명,시군구명,법정동명,...,시군구법정동코드_y,번,지,주소,분류,기업,이름,비고,임차여부,전력사용량
0,697253,4213011700204710,42130117002047,4213011700,2047,10,970171,강원도,원주시,반곡동,...,4213011700,2047,14,강원 원주시 입춘로 130(반곡동 2047-14),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (2사옥),-,-,NaN
1,697253,4213011700204710,42130117002047,4213011700,2047,10,970171,강원도,원주시,반곡동,...,4213011700,2047,10,강원 원주시 혁신로 60(반곡동 2047-10),공공,건강보험심사평가원,건강보험심사평가원 ICT센터\n (1사옥),-,-,NaN
2,697228,421301170018946,42130117001894,4213011700,1894,6,9939,강원도,원주시,반곡동,...,4213011700,1894,6,강원 원주시 건강로 32(반곡동 1894-6),공공,국민건강보험공단,국민건강보험공단 데이터센터,O 자체 데이터센터,-,NaN
3,681992,421103102210000,42110310221000,4211031022,1000,0,12501143,강원도,춘천시,동면 만천리,...,4211031022,1000,0,강원 춘천시 동면 순환대로 1231,민간,NAVER,네이버 데이터센터 각,수력 발전소 통해 전체 전력량 70% 수급,-,NaN

In [7]:
df_3.to_csv("강원도_전력사용량.csv" , mode = 'w' , encoding= 'cp949')